version: "3"
services:
  coturn:
    build:
      context: ../
      dockerfile: ./docker/coturn/debian/Dockerfile
    restart: always
    volumes:
      - ./coturn/turnserver.conf:/etc/turnserver.conf:ro
      - ../certs/privkey.pem:/etc/ssl/turnprivkey.pem:ro
      - ../certs/fullchain.pem:/etc/ssl/certs/turncert.pem:ro
    network_mode: host
    cap_add:
      - NET_BIND_SERVICE

